apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: expenesstracker-secret-store
  namespace: expeness-tracker  # change namespace
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1   # change region
      auth:
        jwt:
          serviceAccountRef:
            name: expenesstracker-secrets-sa
            